name: ichess
version: 1
accesskey: m4mly33kmy
cron:
- description: auto clear
  url: autoclear.php
  schedule: 3 15 * * 1-5
- description: record stock
  url: indexWave.php
  schedule: 0-59 9-11,13-14 * * 1-5
- description: record bkstock
  url: recordbkstock.php
  schedule: 0-59 9-11,13-14 * * 1-5
- description: record cstock
  url: recordcstock.php
  schedule: 0-59 9-11,13-14 * * 1-5
- description: index wave
  url: indexWave2.php
  schedule: 0-59 9-11,13-14 * * 1-5
- description: pref index
  url: prefindex.php
  schedule: 0-59 9-11,13-14 * * 1-5
- description: cal pref
  url: calpref.php
  schedule: 0-59 9-11,13-14 * * 1-5